name: build & Deploy Spring app
on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and deploy springboot for beginners
    runs-on: ubuntu-latest
    steps:
      - name: chekcout code
        uses: actions/checkout@v3

      - name: setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Unit test
        run: mvn -B test --file pom.xml

      - name: Build the application
        run: |
          mvn clean 
          mvn -B package --file pom.xml
